name: e2e-tests

on:
  push:
    branches: [ main, release/* ]
  pull_request:
    branches: [ main, release/* ]

concurrency:
  group: e2e-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:


  install-react:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ 14.x ]
        browser: [ chromium ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - uses: actions/cache@v2
        name: Download any existing cache
        id: yarn-cache
        with:
          path: |
            **/node_modules
            ~/.cache/Cypress
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ matrix.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ matrix.os }}-yarn

      - name: Installing dependencies (if not cached)
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --offline

      - name: Build project
        run: yarn lerna run --stream --ignore @carbon/ibmdotcom-web-components --ignore @carbon/ibmdotcom-services-store build

      - name: Build storybook
        working-directory: packages/react
        run: yarn build-storybook

      - name: Save build folder
        uses: actions/upload-artifact@v2
        with:
          name: storybook-build
          path: packages/react/storybook-static

  react-tests:
    runs-on: macos-latest
    needs: install-react
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2, 3, 4, 5]
        os: [ ubuntu-latest ]
        node-version: [ 14.x ]
        browser: [ chromium, firefox ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'        

      - name: Download the build folders
        uses: actions/download-artifact@v2
        with:
          name: storybook-build
          path: packages/react/storybook-static

      - uses: actions/cache@v2
        name: Retrieve yarn cache
        id: yarn-cache
        with:
          path: |
            **/node_modules
            ~/.cache/Cypress
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ matrix.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ matrix.os }}-yarn
        
      - name: 'Run e2e tests (chromium)'
        if: matrix.browser == 'chromium'      
        uses: cypress-io/github-action@v4
        with:
          working-directory: packages/react
          config-file: tests/e2e-storybook/cypress.json
          start: yarn test:e2e-storybook:test:parallel
          ci-build-id: '${{ github.sha }}-${{ github.workflow }}-react'
          install: false
          browser: chrome
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: carbon-for-ibm-dotcom
          CYPRESS_API_URL: "https://sorry-cypress-director.qfl95m0zv01.us-east.codeengine.appdomain.cloud"
          CYPRESS_CACHE_FOLDER: ~/.cache/Cypress
